project:
  type: website
  output-dir: docs

website:
  title: "Švanda Petr"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Presentations.qmd
      - Resume.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

