---
title: "Resume"
---

### Bc. Petr Švanda

## Scientific expirience

-   **2023 Elaboration and defence of the bachelor thesis:** [Factors affecting pollen transfer effectiveness](https://dspace.cuni.cz/handle/20.500.11956/181062) ŠVANDA, Petr. Faktory ovlivňující efektivitu přenosu pylu. Bakalářská práce, vedoucí Štenc, Jakub. Praha: Univerzita Karlova, Přírodovědecká fakulta, Katedra botaniky, 2023.
-   **Ongoing Master thesis:** Pollen transfer efficiency as a function of pollen deposition and removal
-   **Ongoing** Operating in the [PEG](https://botany.natur.cuni.cz/opylovaci/) scientific team and participating in the experimental parts of the projects
-   **2025 Presentation on Ecoflor conference in León:** Preliminary results of master's thesis on pollen transfer efficiency
-   **2025 Planned internship:** Metabarcoding of pollen on pollinator bodies, under [Paollo Biella](https://pbiella.wixsite.com/pbiella) in University of Milano Bicocca

## Education

-   **2016-2020, high school education:** Gymnázium Pierra de Coubertina, Tábor, Náměstí Františka Křižíka 860

-   **2020–2023, Bachelor's degree:** Charles University in Prague, Faculty of science, Biology, B-BI (0511RA030007)

-   **Ongoing, Master's degree:** Charles University in Prague, Faculty of science, Botany, spec. Geobotanika 23 (MNBBOTGEO23)

## Other work experience

-   **2019 Sub-leader** [of international children camp in Czechia](https://www.volareza.cz/tabory/cz/mezinarodni-detske-tabory-v-roce-2025)

-   **2019 Leader** [of national children camp in Czechia](https://www.volareza.cz/tabory/cz/letni-tabory)

-   **Ongoing Junior salesman** [in LEU brainstimulator, Czechia](https://leubrainstimulator.cz)

## Workshops and other stuff
